/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dtfSol from "./Dtf.sol";
export type { dtfSol };
import type * as iDtfSol from "./IDtf.sol";
export type { iDtfSol };
export type { DtfFactory } from "./DtfFactory";
export type { FundBytecode } from "./FundBytecode";
export type { TestToken } from "./TestToken";
