/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKekBaggiesMutualFund } from "./IKekBaggiesMutualFund";
export type { ILairryFinkFund } from "./ILairryFinkFund";
export type { KekBaggiesMutualFundETHRamp } from "./KekBaggiesMutualFundETHRamp";
export type { LairryFinkETHRamp } from "./LairryFinkETHRamp";
